### ISSUE TITLE
Add a link to the Entity Plus module to README.md

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gdpr_cookies#2]
The Entity Plus module mentioned in the "Dependencies" section has no official release, so people won't find it on the modules page on https://backdropcms.org nor in the Backdrop Project browser. To make it easy to find the module, I suggest to add the link https://github.com/backdrop-contrib/entity_plus.

**Comment by olafgrabienski** [comment]
Great, so we don't need the link anymore!

(Off topic / more general: wouldn't it however be useful to provide links to dependencies?)

**Comment by Graham-72** [comment]
Since the README includes mention of this dependency I think it would be helpful to also include the link, as you suggest. I will add it.
